package dev.jiwon.popup.dailyta;

import dev.jiwon.popup.dailyta.dto.StockItem;

import java.util.List;

public final class StaticStockData {

    private StaticStockData() {}

    public static final List<StockItem> NASDAQ_200 = List.of(
        new StockItem("AAPL", "Apple"),
        new StockItem("MSFT", "Microsoft"),
        new StockItem("NVDA", "NVIDIA"),
        new StockItem("AMZN", "Amazon"),
        new StockItem("META", "Meta Platforms"),
        new StockItem("GOOGL", "Alphabet A"),
        new StockItem("GOOG", "Alphabet C"),
        new StockItem("TSLA", "Tesla"),
        new StockItem("AVGO", "Broadcom"),
        new StockItem("COST", "Costco"),
        new StockItem("NFLX", "Netflix"),
        new StockItem("ADBE", "Adobe"),
        new StockItem("CSCO", "Cisco Systems"),
        new StockItem("INTC", "Intel"),
        new StockItem("AMAT", "Applied Materials"),
        new StockItem("AMD", "Advanced Micro Devices"),
        new StockItem("QCOM", "Qualcomm"),
        new StockItem("ASML", "ASML"),
        new StockItem("MU", "Micron Technology"),
        new StockItem("ADI", "Analog Devices"),
        new StockItem("LRCX", "Lam Research"),
        new StockItem("KLAC", "KLA Corporation"),
        new StockItem("MRVL", "Marvell Technology"),
        new StockItem("NXPI", "NXP Semiconductors"),
        new StockItem("MCHP", "Microchip Technology"),
        new StockItem("ON", "ON Semiconductor"),
        new StockItem("SWKS", "Skyworks Solutions"),
        new StockItem("QRVO", "Qorvo"),
        new StockItem("MPWR", "Monolithic Power Systems"),
        new StockItem("SMCI", "Super Micro Computer"),
        new StockItem("INTU", "Intuit"),
        new StockItem("SNPS", "Synopsys"),
        new StockItem("CDNS", "Cadence Design"),
        new StockItem("ADSK", "Autodesk"),
        new StockItem("WDAY", "Workday"),
        new StockItem("PANW", "Palo Alto Networks"),
        new StockItem("CRWD", "CrowdStrike"),
        new StockItem("FTNT", "Fortinet"),
        new StockItem("ZS", "Zscaler"),
        new StockItem("DDOG", "Datadog"),
        new StockItem("ANSS", "Ansys"),
        new StockItem("TEAM", "Atlassian"),
        new StockItem("OKTA", "Okta"),
        new StockItem("MDB", "MongoDB"),
        new StockItem("CFLT", "Confluent"),
        new StockItem("GTLB", "GitLab"),
        new StockItem("MANH", "Manhattan Associates"),
        new StockItem("PCTY", "Paylocity"),
        new StockItem("PAYC", "Paycom Software"),
        new StockItem("ROP", "Roper Technologies"),
        new StockItem("VRSK", "Verisk Analytics"),
        new StockItem("CTSH", "Cognizant"),
        new StockItem("SBUX", "Starbucks"),
        new StockItem("LULU", "Lululemon Athletica"),
        new StockItem("ORLY", "O'Reilly Automotive"),
        new StockItem("ROST", "Ross Stores"),
        new StockItem("CPRT", "Copart"),
        new StockItem("ODFL", "Old Dominion Freight"),
        new StockItem("FAST", "Fastenal"),
        new StockItem("CTAS", "Cintas"),
        new StockItem("PCAR", "PACCAR"),
        new StockItem("MNST", "Monster Beverage"),
        new StockItem("KHC", "Kraft Heinz"),
        new StockItem("MDLZ", "Mondelez"),
        new StockItem("DLTR", "Dollar Tree"),
        new StockItem("EBAY", "eBay"),
        new StockItem("CHWY", "Chewy"),
        new StockItem("PYPL", "PayPal"),
        new StockItem("COIN", "Coinbase Global"),
        new StockItem("HOOD", "Robinhood Markets"),
        new StockItem("SOFI", "SoFi Technologies"),
        new StockItem("AFRM", "Affirm Holdings"),
        new StockItem("UPST", "Upstart Holdings"),
        new StockItem("PAYX", "Paychex"),
        new StockItem("PLTR", "Palantir Technologies"),
        new StockItem("ARM", "ARM Holdings"),
        new StockItem("APP", "AppLovin"),
        new StockItem("DKNG", "DraftKings"),
        new StockItem("ROKU", "Roku"),
        new StockItem("DUOL", "Duolingo"),
        new StockItem("BMBL", "Bumble"),
        new StockItem("ABNB", "Airbnb"),
        new StockItem("RIVN", "Rivian"),
        new StockItem("LCID", "Lucid Group"),
        new StockItem("TTD", "The Trade Desk"),
        new StockItem("ZM", "Zoom"),
        new StockItem("MTCH", "Match Group"),
        new StockItem("AMGN", "Amgen"),
        new StockItem("GILD", "Gilead Sciences"),
        new StockItem("VRTX", "Vertex Pharmaceuticals"),
        new StockItem("REGN", "Regeneron"),
        new StockItem("ISRG", "Intuitive Surgical"),
        new StockItem("IDXX", "IDEXX Laboratories"),
        new StockItem("DXCM", "DexCom"),
        new StockItem("BIIB", "Biogen"),
        new StockItem("ILMN", "Illumina"),
        new StockItem("MRNA", "Moderna"),
        new StockItem("BNTX", "BioNTech"),
        new StockItem("ALNY", "Alnylam Pharmaceuticals"),
        new StockItem("IONS", "Ionis Pharmaceuticals"),
        new StockItem("NBIX", "Neurocrine Biosciences"),
        new StockItem("EXAS", "Exact Sciences"),
        new StockItem("PODD", "Insulet Corporation"),
        new StockItem("ALGN", "Align Technology"),
        new StockItem("HALO", "Halozyme Therapeutics"),
        new StockItem("INSM", "Insmed"),
        new StockItem("ACAD", "ACADIA Pharmaceuticals"),
        new StockItem("NVCR", "NovaCure"),
        new StockItem("CMCSA", "Comcast"),
        new StockItem("WBD", "Warner Bros. Discovery"),
        new StockItem("SIRI", "Sirius XM"),
        new StockItem("EA", "Electronic Arts"),
        new StockItem("TTWO", "Take-Two Interactive"),
        new StockItem("HON", "Honeywell"),
        new StockItem("TXN", "Texas Instruments"),
        new StockItem("CSX", "CSX Corporation"),
        new StockItem("AEP", "American Electric Power"),
        new StockItem("CEG", "Constellation Energy"),
        new StockItem("EXC", "Exelon"),
        new StockItem("XEL", "Xcel Energy"),
        new StockItem("FANG", "Diamondback Energy"),
        new StockItem("BKR", "Baker Hughes"),
        new StockItem("TRMB", "Trimble"),
        new StockItem("CGNX", "Cognex"),
        new StockItem("IPGP", "IPG Photonics"),
        new StockItem("LITE", "Lumentum Holdings"),
        new StockItem("OLED", "Universal Display"),
        new StockItem("BKNG", "Booking Holdings"),
        new StockItem("MELI", "MercadoLibre"),
        new StockItem("TCOM", "Trip.com Group"),
        new StockItem("BIDU", "Baidu"),
        new StockItem("JD", "JD.com"),
        new StockItem("NTES", "NetEase"),
        new StockItem("PDD", "PDD Holdings"),
        new StockItem("BILI", "Bilibili"),
        new StockItem("IQ", "iQIYI"),
        new StockItem("LI", "Li Auto"),
        new StockItem("FUTU", "Futu Holdings"),
        new StockItem("XPEV", "XPeng"),
        new StockItem("GEHC", "GE HealthCare"),
        new StockItem("INVA", "Innoviva"),
        new StockItem("MSTR", "MicroStrategy"),
        new StockItem("NTAP", "NetApp"),
        new StockItem("WDC", "Western Digital"),
        new StockItem("STX", "Seagate Technology"),
        new StockItem("LOGI", "Logitech"),
        new StockItem("ZBRA", "Zebra Technologies"),
        new StockItem("RMBS", "Rambus"),
        new StockItem("WOLF", "Wolfspeed"),
        new StockItem("AMBA", "Ambarella"),
        new StockItem("ACLS", "Axcelis Technologies"),
        new StockItem("ONTO", "Onto Innovation"),
        new StockItem("SITM", "SiTime"),
        new StockItem("MTSI", "MACOM Technology")
    );

    public static final List<StockItem> KOSPI_100 = List.of(
        new StockItem("005930.KS", "삼성전자"),
        new StockItem("000660.KS", "SK하이닉스"),
        new StockItem("207940.KS", "삼성바이오로직스"),
        new StockItem("005380.KS", "현대차"),
        new StockItem("000270.KS", "기아"),
        new StockItem("068270.KS", "셀트리온"),
        new StockItem("035420.KS", "NAVER"),
        new StockItem("051910.KS", "LG화학"),
        new StockItem("006400.KS", "삼성SDI"),
        new StockItem("028260.KS", "삼성물산"),
        new StockItem("012330.KS", "현대모비스"),
        new StockItem("066570.KS", "LG전자"),
        new StockItem("003550.KS", "LG"),
        new StockItem("032830.KS", "삼성생명"),
        new StockItem("017670.KS", "SK텔레콤"),
        new StockItem("030200.KS", "KT"),
        new StockItem("086790.KS", "하나금융지주"),
        new StockItem("105560.KS", "KB금융"),
        new StockItem("055550.KS", "신한지주"),
        new StockItem("034730.KS", "SK"),
        new StockItem("005490.KS", "POSCO홀딩스"),
        new StockItem("003670.KS", "포스코퓨처엠"),
        new StockItem("009150.KS", "삼성전기"),
        new StockItem("018260.KS", "삼성에스디에스"),
        new StockItem("096770.KS", "SK이노베이션"),
        new StockItem("011200.KS", "HMM"),
        new StockItem("010130.KS", "고려아연"),
        new StockItem("000810.KS", "삼성화재"),
        new StockItem("047050.KS", "포스코인터내셔널"),
        new StockItem("009830.KS", "한화솔루션"),
        new StockItem("010950.KS", "S-Oil"),
        new StockItem("024110.KS", "기업은행"),
        new StockItem("000100.KS", "유한양행"),
        new StockItem("035720.KS", "카카오"),
        new StockItem("352820.KS", "하이브"),
        new StockItem("036570.KS", "엔씨소프트"),
        new StockItem("251270.KS", "넷마블"),
        new StockItem("006800.KS", "미래에셋증권"),
        new StockItem("032640.KS", "LG유플러스"),
        new StockItem("011070.KS", "LG이노텍"),
        new StockItem("161390.KS", "한국타이어앤테크놀로지"),
        new StockItem("051900.KS", "LG생활건강"),
        new StockItem("090430.KS", "아모레퍼시픽"),
        new StockItem("011170.KS", "롯데케미칼"),
        new StockItem("004020.KS", "현대제철"),
        new StockItem("000720.KS", "현대건설"),
        new StockItem("010140.KS", "삼성중공업"),
        new StockItem("042660.KS", "한화오션"),
        new StockItem("329180.KS", "HD현대중공업"),
        new StockItem("267250.KS", "HD현대"),
        new StockItem("078930.KS", "GS"),
        new StockItem("071050.KS", "한국금융지주"),
        new StockItem("015760.KS", "한국전력"),
        new StockItem("000830.KS", "삼성C&T"),
        new StockItem("316140.KS", "우리금융지주"),
        new StockItem("003490.KS", "대한항공"),
        new StockItem("020150.KS", "롯데에너지머티리얼즈"),
        new StockItem("034020.KS", "두산에너빌리티"),
        new StockItem("064350.KS", "현대로템"),
        new StockItem("012450.KS", "한화에어로스페이스")
    );
}
